Fix error: undeclared identifier 'renderSettingsLabel'
The renderSettingsLabel identifier isn't declared anymore after the
recent structural changes, but it's still referenced conditionally in
desktop-ui/settings/cores.cpp and breaks the build if the N64 core is
disabled:

/tmp/ares/desktop-ui/settings/cores.cpp:108:3: error: use of undeclared identifier 'renderSettingsLabel'
  108 |   renderSettingsLabel.setCollapsible(true).setVisible(false);
      |   ^

Remove it to fix the build.